[project]
name = "sc_hackathon_2023"
version = "0.1.0"
description = "Add a short description here"
authors = ["Benjamin Rombaut <benjamin.rombaut@gmail.com>"]
channels = ["conda-forge", "bioconda"]
platforms = ["linux-64"]

[system-requirements]
linux = "3.10.0"

[tasks]

[dependencies]
bioconductor-imcdatasets = "1.8.0.*"
bioconductor-cytomapper = "1.12.0.*"
r-base = "4.3.*"
r-irkernel = "1.3.2.*"
r-biocmanager = "1.30.22.*"
